server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aquareward
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expirationMs: 86400000 # 24 hours
  water:
    dailyBudgetLiters: 120.0
    averageGuestDailyLiters: 150.0
